FROM node:boron
RUN mkdir -p /usr/src/app/lib
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
RUN npm install
COPY ./lib/* /usr/src/app/lib/
COPY server.js /usr/src/app/
COPY config.json /usr/src/app/
RUN node run build -s
EXPOSE 3000
CMD ["node", "server.js"]